import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer'

const poppins = Poppins({weight: "200", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-primary text-white flex flex-col items-center justify-between min-h-screen w-screen overflow-x-hidden`}>
        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  )
}
